blank_issues_enabled: true
contact_links:
  - name: VRChat Canny SDK Bug Reports
    url: https://feedback.vrchat.com/sdk-bug-reports/
    about: Bug in the VRChat SDK? Please report it on Canny.
  - name: VRChat Canny Feature Requests
    url: https://feedback.vrchat.com/feature-requests/
    about: Feature request for the VRChat SDK? Please request it on Canny.
